# SPDX-License-Identifier: GPL-2.0-only

intel-ipu4-objs				+= ipu6.o \
					ipu6-bus.o \
					ipu6-dma.o \
					ipu6-mmu.o \
					ipu6-buttress.o \
					ipu6-cpd.o \
					ipu6-fw-com.o

obj-$(CONFIG_VIDEO_INTEL_IPU4)		+= intel-ipu4.o

intel-ipu4-isys-objs			+= ipu6-isys.o \
					ipu6-isys-csi2.o \
					ipu6-fw-isys.o \
					ipu6-isys-video.o \
					ipu6-isys-queue.o \
					ipu6-isys-subdev.o

obj-$(CONFIG_VIDEO_INTEL_IPU4)		+= intel-ipu4-isys.o
