# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_VIDEO_IPU4_KUNIT_TESTS) += ipu4_format_kunit.o
obj-$(CONFIG_VIDEO_IPU4_KUNIT_TESTS) += ipu4_bayer_kunit.o
obj-$(CONFIG_VIDEO_IPU4_KUNIT_TESTS) += ipu4_mmu_kunit.o

ccflags-y += -I$(src)/..
