/* SPDX-License-Identifier: GPL-2.0-only */
/*
   IPU4 values coming from
   drivers/media/pci/intel/ipu4/ipu-platform-isys-csi2-reg.h
   in linux 4.x driver

   Copyright (C) 2023 Intel Corporation
*/

#ifndef IPU6_PLATFORM_ISYS_CSI2_REG_H
#define IPU6_PLATFORM_ISYS_CSI2_REG_H

#define CSI_REG_BASE			0x220000

/* CSI Port Genral Purpose Registers */
#define CSI_REG_PORT_GPREG_SRST                 0x0
#define CSI_REG_PORT_GPREG_CSI2_SLV_REG_SRST    0x4
#define CSI_REG_PORT_GPREG_CSI2_PORT_CONTROL    0x8

/*
 * Port IRQs mapping events:
 * IRQ0 - CSI_FE event
 * IRQ1 - CSI_SYNC
 * IRQ2 - S2M_SIDS0TO7
 * IRQ3 - S2M_SIDS8TO15
 */
#define CSI_PORT_REG_BASE_IRQ_CSI               0x80
#define CSI_PORT_REG_BASE_IRQ_CSI_SYNC          0xA0

#define CSI_PORT_REG_BASE_IRQ_EDGE_OFFSET	0x0
#define CSI_PORT_REG_BASE_IRQ_MASK_OFFSET	0x4
#define CSI_PORT_REG_BASE_IRQ_STATUS_OFFSET	0x8
#define CSI_PORT_REG_BASE_IRQ_CLEAR_OFFSET	0xc
#define CSI_PORT_REG_BASE_IRQ_ENABLE_OFFSET	0x10
#define CSI_PORT_REG_BASE_IRQ_LEVEL_NOT_PULSE_OFFSET	0x14

#define CSI_RX_NUM_ERRORS_IN_IRQ		20

#define IPU_CSI_RX_IRQ_FS_VC(chn)	(1 << ((chn) * 2))
#define IPU_CSI_RX_IRQ_FE_VC(chn)	(2 << ((chn) * 2))

/* PPI2CSI */
#define CSI_REG_PPI2CSI_ENABLE				0x200
#define CSI_REG_PPI2CSI_CONFIG_PPI_INTF			0x204
#define PPI_INTF_CONFIG_NOF_ENABLED_DLANES_MASK		GENMASK(4, 3)

/* CSI_FE */
#define CSI_REG_CSI_FE_ENABLE                   0x280
#define CSI_REG_CSI_FE_MODE                     0x284
#define CSI_REG_CSI_FE_MUX_CTRL                 0x288
#define CSI_REG_CSI_FE_SYNC_CNTR_SEL            0x290

enum CSI_FE_INPUT_SELECTOR {
	CSI_SENSOR_INPUT = 0,
	CSI_MIPIGEN_INPUT = 1,
};

enum CSI_FE_SYNC_CNTR_SEL_TYPE {
	CSI_CNTR_SENSOR_LINE_ID = BIT(0),
	CSI_CNTR_INT_LINE_PKT_ID = ~CSI_CNTR_SENSOR_LINE_ID,
	CSI_CNTR_SENSOR_FRAME_ID = BIT(1),
	CSI_CNTR_INT_FRAME_PKT_ID = ~CSI_CNTR_SENSOR_FRAME_ID,
};

#define CSI_REG_HUB_DRV_ACCESS_PORT(id)	(CSI_REG_BASE + 0x18018 + (id) * 4)
#define CSI_REG_HUB_FW_ACCESS_PORT(ofs, id)	\
					(CSI_REG_BASE + (ofs) + (id) * 4)

#define IPU4_ISYS_MAX_CSI2_LEGACY_PORTS	4
#define IPU4_ISYS_UNISPART_IRQ_CSI2(port)		\
	({ typeof(port) __port = (port); \
	__port < IPU4_ISYS_MAX_CSI2_LEGACY_PORTS ?	\
	((0x8) << __port) :					\
	(0x800 << (__port - IPU4_ISYS_MAX_CSI2_LEGACY_PORTS)); })

/* IRQ-related registers specific to each of the four CSI receivers */
#define CSI2_REG_CSI2PART_IRQ_EDGE			0x400
#define CSI2_REG_CSI2PART_IRQ_MASK			0x404
#define CSI2_REG_CSI2PART_IRQ_STATUS			0x408
#define CSI2_REG_CSI2PART_IRQ_CLEAR			0x40c
#define CSI2_REG_CSI2PART_IRQ_ENABLE			0x410
#define CSI2_REG_CSI2PART_IRQ_LEVEL_NOT_PULSE		0x414
#define CSI2_CSI2PART_IRQ_CSIRX				0x10000

#define CSI2_REG_CSIRX_IRQ_EDGE				0x500
#define CSI2_REG_CSIRX_IRQ_MASK				0x504
#define CSI2_REG_CSIRX_IRQ_STATUS			0x508
#define CSI2_REG_CSIRX_IRQ_CLEAR			0x50c
#define CSI2_REG_CSIRX_IRQ_ENABLE			0x510
#define CSI2_REG_CSIRX_IRQ_LEVEL_NOT_PULSE		0x514
#define CSI2_CSIRX_NUM_ERRORS				17

#define CSI2_REG_CSI2S2M_IRQ_EDGE			0x600
#define CSI2_REG_CSI2S2M_IRQ_MASK			0x604
#define CSI2_REG_CSI2S2M_IRQ_STATUS			0x608
#define CSI2_REG_CSI2S2M_IRQ_CLEAR			0x60c
#define CSI2_REG_CSI2S2M_IRQ_ENABLE			0x610
#define CSI2_REG_CSI2S2M_IRQ_LEVEL_NOT_PULSE		0x614

#define CSI2_IRQ_FS_VC(chn)				(1 << ((chn) * 4))
#define CSI2_IRQ_FE_VC(chn)				(2 << ((chn) * 4))

#define CSI2_REG_CSI_RX_ENABLE				0x00
#define CSI2_CSI_RX_ENABLE_ENABLE			0x01
/* Enabled lanes - 1 */
#define CSI2_REG_CSI_RX_NOF_ENABLED_LANES		0x04
#define CSI2_REG_CSI_RX_CONFIG				0x08
#define CSI2_CSI_RX_CONFIG_RELEASE_LP11			0x1
#define CSI2_CSI_RX_CONFIG_DISABLE_BYTE_CLK_GATING	0x2
#define CSI2_REG_CSI_RX_DLY_CNT_TERMEN_CLANE		0x2c
#define CSI2_REG_CSI_RX_DLY_CNT_SETTLE_CLANE		0x30
/* 0..3 */
#define CSI2_REG_CSI_RX_DLY_CNT_TERMEN_DLANE(n)		(0x34 + (n) * 8)
#define CSI2_REG_CSI_RX_DLY_CNT_SETTLE_DLANE(n)		(0x38 + (n) * 8)

#endif /* IPU6_ISYS_CSI2_REG_H */
