# SPDX-License-Identifier: GPL-2.0-only

intel-ipu4-objs				+= ipu6.o \
					ipu6-bus.o \
					ipu6-dma.o \
					ipu6-mmu.o \
					ipu6-buttress.o \
					ipu6-cpd.o

obj-$(CONFIG_VIDEO_INTEL_IPU4)		+= intel-ipu4.o